### ISSUE TITLE
Track overridden or monkey patched code by commit hash from upstream repo

### ISSUE THREAD

**Issue by agritheory** [agritheory/test_utils#13]

**Comment by fproldan** [comment]
@agritheory https://github.com/fproldan/overrides

**Comment by fproldan** [comment]
@agritheory  https://github.com/diamorafaela/track-overrides

**Comment by agritheory** [comment]
@fproldan I would like to import this available as pre-commit hook via this repo. I propose that we add it as a dependency and wrap it
