### ISSUE TITLE
Calculate customization hash ignores HRSM customizations

### ISSUE THREAD

**Issue by agritheory** [agritheory/test_utils#31]
#17 Won't detect changes to HRMS customizations without some help. 

I propose we abstract the [HRMS lookup](https://github.com/agritheory/test_utils/blob/main/test_utils/pre_commit/validate_customizations.py#L36-L52) into a separate function so we can incorporate it into the workflow. 

We can check if HRMS is installed like this:
```python
try: 
	import hrms
	hrms_installed = True
except ModuleNotFoundError as e:
	hrms_installed = False
```

**Comment by MyuddinKhatri** [comment]
> #17 Won't detect changes to HRMS customizations without some help.
> 
> I propose we abstract the [HRMS lookup](https://github.com/agritheory/test_utils/blob/main/test_utils/pre_commit/validate_customizations.py#L36-L52) into a separate function so we can incorporate it into the workflow.
> 
> We can check if HRMS is installed like this:
> 
> ```python
> try: 
> 	import hrms
> 	hrms_installed = True
> except ModuleNotFoundError as e:
> 	hrms_installed = False
> ```

@agritheory rather than doing this as we already have a list of installed apps, [customize.py-L17](https://github.com/agritheory/test_utils/blob/c5eee28f4ae6c0f48ad11e0e38ff7745d329326a/test_utils/utils/customize.py#L17) can we use this directly?

**Comment by MyuddinKhatri** [comment]
@agritheory Can this be marked as completed.
