### ISSUE TITLE
Add `pytest-cov` to all tests via conftest boilerplate import

### ISSUE THREAD

**Issue by agritheory** [agritheory/test_utils#4]
https://pypi.org/project/pytest-cov/

This will also have to be added to a general-purpose pytest GHA

**Comment by MyuddinKhatri** [comment]
@agritheory I was able to get coverage report after adding below snippet to `pyproject.toml` by simply running `pytest ./apps/beam/beam/tests`

`[tool.pytest.ini_options]
addopts = "--cov={app_name} --cov-report term"`
