### ISSUE TITLE
Document management of a Frappe app with poetry

### ISSUE THREAD

**Issue by agritheory** [agritheory/test_utils#6]
Flit has several bugs that takes extra management and generally doesn't work all that well with Frappe apps. We should be using poetry instead. 

- Convert pyproject.toml to use poetry (document process, script if appropriate)
- Document how to a new dependency (Flit has no API for this)

**Comment by MyuddinKhatri** [comment]
@agritheory can we mark this issue as completed or we should keep this until we make changes in other repos?

**Comment by agritheory** [comment]
@MyuddinKhatri We can mark it as complete. I think we want to raise one ticket per repo for migrating to test_utils with a checklist - that's enough visibility and not that much noise.
