### ISSUE TITLE
Partition helper

### ISSUE THREAD

**Issue by agritheory** [agritheory/test_utils#74]
In many table definitions, it may be of benefit to partition based on the transaction's date range (calendar year 2023 for example).

This function would accept an configuration in `hooks.py` that would define doctypes that would need to be subject to this partition logic.

This may include (for example) creating a column in Sales Invoice Item for `transaction_datetime` that is a combination of the parent record's `transaction_date` + `transaction_time` fields. This could be solved by adding a "*" doc_hook to ensure this data exists.

[This documentation](https://mariadb.com/kb/en/partitioning-overview/) gives a pretty clear recipe for how this would work. We can create the partition as a doc_hook on Fiscal Year, or fiscal year + quarter, and on disabled/ enabled on Item, Customer and Supplier.

- Partial restore to reduce recovery downtimes [docs](https://mariadb.com/kb/en/restoring-individual-tables-and-partitions-with-mariabackup/)
- Better performance for in-partition data

**Comment by agritheory** [comment]
More background: https://www.youtube.com/watch?v=XtFqegG1v7g

Sachin talk here about the overall architecture and doesn't get into details of the partition implementation.

**Comment by MyuddinKhatri** [comment]
I started looking into creating Partition on the table, but I am facing issues 
Error - `A PRIMARY KEY must include all columns in the table's partitioning function`,  

After I added column -  `creation` as the primary key along with the name, I got another error while creating the Partition
Error -  `A UNIQUE INDEX must include all columns in the table's partitioning function`  
Currently, I am trying this on table User, 
```
ALTER TABLE `tabUser` 
PARTITION BY RANGE (YEAR(creation)) 
(PARTITION p2022 VALUES LESS THAN (2023),
PARTITION p2023 VALUES LESS THAN (2024),
PARTITION p2024 VALUES LESS THAN (2025));
```
I was able to create the partitions on Sales Order as it had column `transaction_date`, added transaction_date as the primary key along with the name, 
```
ALTER TABLE `tabSales Order`
PARTITION BY RANGE (YEAR(`transaction_date`)) (
    PARTITION p2022 VALUES LESS THAN (2023),
    PARTITION p2023 VALUES LESS THAN (2024),
    PARTITION p2024 VALUES LESS THAN (2025)
);
```

I am still working on it, once I have this it will be easier to implement the helper function to create the Partition on the tables.

Few questions once we are able to get the Partitions on the table for restoring database

I am not sure about -
- how it will be handled on site migrate?(will have to test this once i am able to get the partition for any one of the Table)
- Taking a partial backup based on partition and Restoring partial backup based on table partitions (not sure if this is even a right question)

@agritheory Can you please check the above comment, and let me know your thoughts.

**Comment by agritheory** [comment]
@MyuddinKhatri Two small notes - the PK should be `name` as it is for every Frappe doctype. There's no reason to be so brief with the partition name, we can do things like `fiscal_year_2020`.

Can you try partitioning Item/Customer/Supplier on `modified` instead? We can then update the modified to an arbitrary setpoint in the past and setup a special restore point for "before that" via a SQL dump that would run after migrate (not bench backup).

**Comment by MyuddinKhatri** [comment]
> @MyuddinKhatri Two small notes - the PK should be `name` as it is for every Frappe doctype. There's no reason to be so brief with the partition name, we can do things like `fiscal_year_2020`.
> 
> Can you try partitioning Item/Customer/Supplier on `modified` instead? We can then update the modified to an arbitrary setpoint in the past and setup a special restore point for "before that" via a SQL dump that would run after migrate (not bench backup).

@agritheory If we directly try to create a partition on any of the table then it throws - `A PRIMARY KEY must include all columns in the table's partitioning function`

**Comment by fproldan** [comment]
@agritheory @MyuddinKhatri 

I have never used partitioning but I read that the column we want to use for partitioning (`transaction_date` i.e) must be in every **primary key** or **unique key** in the table, so it doesn't seem feasible.

**Comment by MyuddinKhatri** [comment]
> @agritheory @MyuddinKhatri 
> 
> 
> 
> I have never used partitioning but I read that the column we want to use for partitioning (`transaction_date` i.e) must be in every **primary key** or **unique key** in the table, so it doesn't seem feasible.
> 
> 
> 
> More info [here](https://dev.mysql.com/doc/refman/8.4/en/partitioning-limitations-partitioning-keys-unique-keys.html)
> 
> 
> 
> > The rule governing this relationship can be expressed as follows: All columns used in the partitioning expression for a partitioned table must be part of every unique key that the table may have.
> 
> 
> 
> > In other words, every unique key on the table must use every column in the table's partitioning expression. (This also includes the table's primary key, since it is by definition a unique key.
> 
> 
> 
> 
> 
> 

@fproldan yes agreed, while creating partition it expects the column to be a Primary Key.

**Comment by agritheory** [comment]
My instance doesn't show any other keys than this. I think removing or altering UNIQUE constraints is pretty straightforward though. 
```
 | tabSales Order                                    | PRIMARY                           | name                             | PRIMARY KEY     |
```

**Comment by fproldan** [comment]
@agritheory yes, I was able to execute the partitions after alter the primary key.
