### ISSUE TITLE
Automatically make a PR via GitHub Action to translate documentation

### ISSUE THREAD

**Issue by agritheory** [agritheory/test_utils#9]
There are several GHAs that are close to target on this, I think we should adapt one that makes sense.

The change to the {repo}/docs folder would ideally be:
{repo}/docs/{major_version}/{lang}/index.md

For example:
check_run/docs/version-15/en/index.md

**Comment by agritheory** [comment]
@fproldan I was thinking about how to detect what languages should be managed by the app and I have two ideas:

1. Use hooks.py with whatever configuration data structure makes sense, without secrets
2. Use the translation CSVs to indicate the managed languages

The config approach should be the same between this issue and  #23

**Comment by fproldan** [comment]
@agritheory 

Here is a Frappe app in which you can see and test the GA: https://github.com/fproldan/translations
The readme has the configuration steps to apply it to other apps, also a TODO list with improvements we might want.
